### ISSUE TITLE
UI - 탭바 및 배경 색상 변경

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#11]
# 개요
탭바 및 배경의 색상을 변경합니다.

## Tasks
- [x] bkBackgroundColor, bkTabBarBackgroundColor 변경
- [x] Assets에 저장된 컬러 변경
- [x] 백그라운드, 폰트에 필요한 색상 추가

## 작업 환경
* Xcode Xcode 15.0.1
