### ISSUE TITLE
Search - 검색결과 도서 이미지의 비율 변경

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#25]
# 개요
도서 검색 결과로 보여주는 책 표지의 이미지 비율을 변경합니다.

## Tasks

- [x] UIImageView 공식문서 살피기
  - [x] content mode 알아보기
  - [x] content mode 수정
- [x] UITableViewCell 공식문서 살피기
- [x] 레이아웃 수정
  - [x] Dynamic Type 적용 해제

## 작업 환경
Xcode Version 15.1 

## 참고자료
- [UIImageView 공식문서](https://developer.apple.com/documentation/uikit/uiimageview)
- [UITableViewCell 공식문서](https://developer.apple.com/documentation/uikit/uitableviewcell)
