### ISSUE TITLE
Search - 검색결과에 따른 도서 상세정보 뷰 제작

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#27]
# 개요
검색결과에 따른 도서의 상세정보를 보여주는 뷰를 만듭니다.

## Tasks
- [x] 도서의 상세 정보를 ISBN으로 검색하여 가져오는 메서드 구현
    - [x] 올바른 데이터 수신 확인
    - [x] 도서 상세 정보 수신을 위한 모델 수정
      - [x] 기존 모델과 통합
- [x] 새로운 스크린(viewController)을 navigationController에 push
    - [x] 새로운 스크린에 라벨, 이미지뷰 레이아웃 적용
    - [x] 새로운 스크린에 네비게이션 바 버튼 추가
