### ISSUE TITLE
Login - Apple 로그인 구현

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#31]
# 개요
Apple Login을 구현합니다.

## Tasks
- [ ] Sign in with Apple 공식문서 읽어보기
- [ ] Authentication Services Framework 공식문서 읽어보기
- [ ] Keychain 공식문서 읽어보기
    - [ ] Keychain 담당 싱글턴 객체 구현

## 작업 환경
Xcode Version 15.2
## 참고자료
- [Apple Developer - Implementing User Authentication with Sign in with Apple](https://developer.apple.com/documentation/sign_in_with_apple/implementing_user_authentication_with_sign_in_with_apple)
- [Apple Developer - Authentication Services](https://developer.apple.com/documentation/authenticationservices)
- [Apple Developer - Keychain Services](https://developer.apple.com/documentation/security/keychain_services)
