### ISSUE TITLE
UI - 컬렉션뷰/Segmented Control 사용한 뷰 만들기

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#35]
# 개요
컬렉션뷰와 Segmented Control을 사용하여 내가 저장한 책들을 보여주는 뷰를 만듭니다.

## Tasks

- [x] Segmented Control
    - [x] Custom Segmented Control 사용

- [x] 내 책장 View: 도서 검색 이후 책장에 추가한 책들을 보여줍니다.
    - [x] Collection View
    - [x] 데이터 연결
    - [x] Collection View 디자인

- [x] 책바구니 View: 도서 검색 이후 책바구니에 추가한 책들을 보여줍니다.
    - [x] Collection View
    - [x] 데이터 연결

## 작업 환경
Xcode Version 15.2

## 참고자료

공식문서
- [Collection Views](https://developer.apple.com/documentation/uikit/views_and_controls/collection_views)
- [UICollectionView](https://developer.apple.com/documentation/uikit/uicollectionview)
- [UIPageViewController](https://developer.apple.com/documentation/uikit/uipageviewcontroller)

아티클/블로그
- [UIPageViewController](https://ios-development.tistory.com/623)
- [Custom Segmented Control 만들기](https://ios-development.tistory.com/963)
