### ISSUE TITLE
Feat - 도서 기록 뷰 및 문장, 생각 추가 뷰 추가

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#37]
# 개요
내 책장 탭에서 도서를 눌렀을 때 보여줄 도서 기록 뷰와
생각 및 문장을 추가할 수 있는 뷰를 추가합니다.

## Tasks

- 이전 도서 정보 뷰 수정 (BookInformationViewController -> BookDetailInformationViewController)

- 내 책장
  - [x] 내 도서 뷰(MyBookViewController)
    - [x] 기존 MyBookViewController 이름 변경 -> MyBookCaseViewController
    - [x] 새로운 ViewController -> MyBookViewController
    - [x] 문장 추가 버튼
    - [x] 생각 추가 버튼

- 책 바구니
  - [x] 도서 정보 뷰 (BookDetailInformationViewController)
  - [x] 내 책장으로 이동 버튼

## 작업 환경
Xcode Version 15.2
