### ISSUE TITLE
Feat - 달력탭 기록 수정시 도서 정보 확인 기능

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#41]
# 개요
달력탭의 기록을 수정하는 할 때 도서 정보를 확인할 수 있는 기능을 구현합니다.

## Tasks
- [x] 달력탭에서 기록 수정 뷰에 접근시 Bar Button Item 추가
- [x] 달력탭 에러처리
- [x] 이미지 로딩중 Indicator 처리
- [x] 기타 작업(코드 제거, 리팩토링)
## 작업 환경
Xcode Version 15.2
