### ISSUE TITLE
Feat - 설정 탭 구현 및 프로젝트 마무리

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#43]
# 개요
설정 탭을 구현합니다.

## Tasks
- [x] 설정 탭 테이블뷰 생성
- [x] 테이블뷰 셀 생성 및 구현
    - [x] 문의하기/의견 보내기(mailto)
    - [x] 앱 버전 표기
    - [x] 개인정보 처리방침
- [x] 오픈소스 라이선스 고지하기
- [x] Firebase Analytics 적용
- [x] Firebase Crashlytics 적용
- [x] 코드 정리(불필요한 코드 제거, Format 통일)
- [x] 앱 아이콘 추가

## 작업 환경
- Xcode Version 15.2
