### ISSUE TITLE
Network - 알라딘 OpenAPI

### ISSUE THREAD

**Issue by jekyun-park** [jekyun-park/Bookie#9]
# 개요
알라딘 Open API를 활용한 도서 검색 API 작업을 진행합니다.

## Tasks
- [x] OpenAPI 사용을 위한 싱글턴 객체 생성
- [x] API 인증키 은닉화
- [x] 검색 메서드 구현

## 작업 환경
- Xcode 15.0.1
- Swift 5.8.1

## 참고자료
- [알라딘 OpenAPI 매뉴얼](https://docs.google.com/document/d/1mX-WxuoGs8Hy-QalhHcvuV17n50uGI2Sg_GHofgiePE/edit#heading=h.wzyr9o7mof2u)
